# Generated by Django 4.2.6 on 2023-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_product_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=400)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
