# Generated by Django 4.2.6 on 2023-11-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0003_contact_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_query',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
