# Generated by Django 4.2.6 on 2023-11-09 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_alter_contact_query_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_query',
            name='date_time',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 11, 9, 16, 49, 25, 152636)),
        ),
    ]
