# Generated by Django 4.2.6 on 2023-11-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_alter_contact_query_date_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_Query',
        ),
    ]
